# Generated by Django 5.2.6 on 2026-02-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_providerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
            ],
            options={
                'verbose_name': 'Doctor/Provider',
                'verbose_name_plural': 'Doctors/Providers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='specialization',
            field=models.CharField(blank=True, help_text='e.g. Cardiology, Neurology', max_length=100),
        ),
    ]
